version: '3'
services:
  node:
    image: node:12
    container_name: react-node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./:/usr/src/app
    command: bash -c "yarn && yarn start"
    ports:
      - "3000:3000"